apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: on0x0ne0p-python-gitops
  description: This is GitOps manifest for on0x0ne0p-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: on0x0ne0p-python
    backstage.io/kubernetes-id: on0x0ne0p-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:on0x0ne0p-python
