apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: on0x0ne0p-python
  janus-idp.io/tekton: on0x0ne0p-python
  backstage.io/kubernetes-id: on0x0ne0p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: on0x0ne0p-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
